### ISSUE TITLE
The example website is unavailable

### ISSUE THREAD

**Issue by mtcoafun** [Tarikul-Islam-Anik/Telegram-Animated-Emojis#5]
the website is now like this :(

<img width="724" alt="image" src="https://github.com/user-attachments/assets/a7493291-e9c0-465e-8c0c-4c4b4a574899" />

**Comment by Tarikul-Islam-Anik** [comment]
Hello, @mtcoafun!

Thanks for pointing out the issue. That domain has an issue and I had to change the domain name. It can be found here 🔗[https://telegram-emojis.vercel.app/](https://telegram-emojis.vercel.app/)

Regards,
Tarikul
